

export const TABLE = {
    USER: "USER",
    CAR: "VEHICLE",
    CAR_MODEL: "MODEL",
    CAR_MARQUE: "MARQUE",
    TYPE_DEPENSE: "TYPE_DEPENSE",
    SOUS_TYPE_DEPENSE: "SOUS_TYPE_DEPENSE",
    DEPENSE: "DEPENSE",
}